#!/bin/bash
# Script to prepare Firebase credentials for Railway deployment
# This converts the JSON service account key into an environment variable format

echo "🔐 Firebase Credentials Setup for Railway"
echo "=========================================="
echo ""
echo "Step 1: Get your Firebase Service Account Key"
echo "  1. Go to Firebase Console: https://console.firebase.google.com"
echo "  2. Select your project 'citizensafe-437b0'"
echo "  3. Click Project Settings (gear icon) > Service Accounts"
echo "  4. Click 'Generate New Private Key' (download JSON file)"
echo "  5. You'll get a file like 'citizensafe-437b0-xxxxx.json'"
echo ""
echo "Step 2: Convert JSON to environment variable"
echo "  macOS/Linux:"
echo "    cat /path/to/citizensafe-437b0-xxxxx.json | tr '\n' ' '"
echo ""
echo "  Windows (PowerShell):"
echo "    [System.IO.File]::ReadAllText('C:\\path\\to\\file.json') -replace '\\r?\\n', ' '"
echo ""
echo "Step 3: Copy the entire JSON output (keep spaces)"
echo ""
echo "Step 4: In Railway Dashboard:"
echo "  1. Open your project"
echo "  2. Click on Backend Service"
echo "  3. Go to Variables tab"
echo "  4. Add new variable:"
echo "     Key: GOOGLE_APPLICATION_CREDENTIALS"
echo "     Value: /tmp/firebase-key.json"
echo ""
echo "  5. Add another variable:"
echo "     Key: FIREBASE_SERVICE_ACCOUNT_KEY"
echo "     Value: {paste your entire JSON here}"
echo ""
echo "Step 5: Add startup script in Dockerfile"
echo "  This creates the credentials file at runtime from the env var"
echo ""
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT: Never commit your service account key to GitHub!"
echo "   It contains sensitive credentials. Use Railway Variables instead."
echo ""
